import java.io.IOException;
 

public class Main {
 
    public static void main(String[] args) throws IOException {
 
      import java.io.IOException;
 
public class Main {
 
    public static void main(String[] args) throws IOException {
 
     int A;
     int B;
     int SOMA;
     
      Scanner sc = new Scanner(System.in);
     
     System.out.println("A");
     A = sc.nextInt();
     
     System.out.println("B");
     B = sc.nextInt();
    
     SOMA = A+B;

     System.out.println("SOMA = " + (A+B));
     
    }
}
     
    }
    
    
 
}
